# Generated by Django 4.1.7 on 2023-03-02 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/defaulImg.png', null=True, upload_to='profiles/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
