# Generated by Django 4.1.7 on 2023-03-03 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('part_num', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('car_image', models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='parts_images/')),
                ('price', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
