# Generated by Django 4.1.7 on 2023-03-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='car_image',
            new_name='part_image',
        ),
    ]
