# Generated by Django 4.1.7 on 2023-03-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_bikes_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_image2',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='bike_image3',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='bike_image4',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image2',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image3',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image4',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='truck_image2',
            field=models.ImageField(blank=True, default='933_ps.jpg', null=True, upload_to='truck_images/'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='truck_image3',
            field=models.ImageField(blank=True, default='933_ps.jpg', null=True, upload_to='truck_images/'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='truck_image4',
            field=models.ImageField(blank=True, default='933_ps.jpg', null=True, upload_to='truck_images/'),
        ),
    ]
