# Generated by Django 4.1.7 on 2023-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_bikes_bike_image2_bikes_bike_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trucks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
